Added (very basic) functionality to handle special workspaces
nwg-piotr/nwg-dock-hyprland pull request #13
Opened 2023-08-06 10:08 UTC by levnikmyskin

Hi :)
Currently, windows residing in a [special workspace](https://wiki.hyprland.org/Configuring/Dispatchers/#special-workspace) will be treated by nwg-dock just like any other window, triggering `focuswindow`. This does not work of course.

What I did at the moment is simply to actually dispatch `togglespecialworkspace`. Now when we click on a client icon residing in a special workspace, the client will be moved in and out of the special workspace (it won't be focused), together with whatever else might be in the special workspace. This works well, I guess, for users that will only put one and only one client in a special workspace. 

That said, I know that this is probably not ready for merging, but I'm still opening this pull request for discussion.

2023-08-06 13:07 UTC, nwg-piotr reviewed
Doesn't seem to work for me. I have not enough time to test it properly (leaving for a lake!), but shouldn't it be just:

```go
if strings.HasPrefix(t.Workspace.Name, "special") {
	cmd = "dispatch togglespecialworkspace"
}
```
?

2023-08-07 11:46 UTC, levnikmyskin commented
Ah damn, I totally forgot about the unnamed special workspace, I always give names :smiling_face_with_tear: 
It should work now. We cannot use your code because there are also named special workspaces (for instance special:something). 
Basically, if we want to toggle the special workspaces there are two syntaxes:

- `togglespecialworkspace` for unnamed special workspaces (the ones you create by simply using `movingtoworkspace special`);
- `togglespecialworkspace something` for named special workspaces (the ones you create by using `movingotworkspace special:something`)

2023-08-07 18:28 UTC, nwg-piotr commented
Very well. When your PR is finished, it'll have to wait until I'm back home. Just started my holiday over the lake, w/ only an old laptop and no coding tools.

2023-08-08 10:45 UTC, levnikmyskin commented
No worries, enjoy your vacation! The PR should be ok now, I'll mark it as ready for review

2023-08-16 21:20 UTC, nwg-piotr requested changes
This is not bad, but needs some improvement.

1. If we open an app, e.g. Mousepad, and move it to the special workspace, then use the "New window" entry, we have 2 instances, of which one is on the special workspace and the other is not. For some reason, if we obtain `instance.Workspace.Name` inside the lambda that connects the "activate" signal, this will always be the same first value. Use of the `wsName` helper variable before the lambda helps. I have no idea why it happens in gotk3, but it does happen.
2. In the same example, in the context menu we have 2 instances of Mousepad, and no idea whether one of them there is on the special workspace. I suggest to prefix the label with e.g. "S| " to make it better visible.

```go
func clientMenu(class string, instances []client) gtk.Menu {
	menu, _ := gtk.MenuNew()

	iconName, err := getIcon(class)
	if err != nil {
		log.Warn(err)
	}
	for _, instance := range instances {
		menuItem, _ := gtk.MenuItemNew()
		hbox, _ := gtk.BoxNew(gtk.ORIENTATION_HORIZONTAL, 6)
		image, _ := gtk.ImageNewFromIconName(iconName, gtk.ICON_SIZE_MENU)
		hbox.PackStart(image, false, false, 0)
		title := instance.Title
		if len(title) > 20 {
			title = title[:20]
		}
		wsName := instance.Workspace.Name
		var label *gtk.Label
		if strings.HasPrefix(wsName, "special") {
			label, _ = gtk.LabelNew(fmt.Sprintf("S| %s (%v)", title, instance.Workspace.Id))
		} else {
			label, _ = gtk.LabelNew(fmt.Sprintf("%s (%v)", title, instance.Workspace.Id))
		}
		hbox.PackStart(label, false, false, 0)
		menuItem.Add(hbox)
		menu.Append(menuItem)
		a := instance.Address
		menuItem.Connect("activate", func() {
			cmd := fmt.Sprintf("dispatch focuswindow address:%s", a)
			if strings.HasPrefix(wsName, "special") {
				_, specialName, _ := strings.Cut(wsName, "special:")
				cmd = fmt.Sprintf("dispatch togglespecialworkspace %s", specialName)
			}
			reply, _ := hyprctl(cmd)
			log.Debugf("%s -> %s", cmd, reply)
		})

	}
	menu.ShowAll()
	return *menu
}
```

2023-08-18 23:02 UTC, nwg-piotr commented
Since there are some other fixes waiting to be released, I'll merge your PR and add the changes I requested myself.

2023-08-18 23:02 UTC, merged

2023-08-19 08:48 UTC, levnikmyskin commented
Thank you very much! I've been busy with moving these days and I totally missed your message